[tool.poetry]
name = "trust-eval"
version = "0.1.0"
description = ""
authors = ["Shang Hong Sim <simshanghong@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.13"
vllm = "^0.6.6.post1"
peft = "^0.14.0"
fuzzywuzzy = "^0.18.0"
python-levenshtein = "^0.26.1"
scipy = "^1.14.1"
colorlog = "^6.9.0"
nltk = "^3.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
