[tool.poetry]
name = "trust-eval"
version = "0.1.0"
description = ""
authors = ["Shang Hong Sim <simshanghong@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
