# Model arguments
# model_init_kwargs:
model_name_or_path: meta-llama/Llama-2-7b-chat-hf # change this
model_revision: main
torch_dtype: bfloat16
trust_remote_code: True
attn_implementation: flash_attention_2  #sdpa
# use_peft: True

# Data training arguments
dataset_mixer:
  "/home/shanghong/work/trust-align/data/SFT_Cited_Text": 1.0
dataset_splits:
  - train
  - test
preprocessing_num_workers: 1
truncation_side: "left"

# SFT trainer config
dataset_text_field: messages
packing: false
eval_packing: false
output_dir: /mnt/data1/shanghong/shared_models # change this
num_train_epochs: 2
max_steps: -1
bf16: true
per_device_train_batch_size: 8  # Llama2:12, Llama3: 4
per_device_eval_batch_size: 4  # Llama2:4, Llama3: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
gradient_accumulation_steps: 3
max_grad_norm: 1.0
learning_rate: 2.0e-05
optim: adamw_torch
lr_scheduler_type: cosine
warmup_ratio: 0.1
group_by_length: true
do_eval: true
batch_eval_metrics: true
eval_strategy: "steps"
eval_steps: 10
log_level: info
logging_steps: 2
logging_strategy: steps
max_seq_length: 2048
overwrite_output_dir: true
remove_unused_columns: true
run_name: llama2-7b-sft # modelname-size-sft/dpo convention
report_to:
  - "wandb"
save_strategy: "steps"
save_steps: 20
save_only_model: True
save_total_limit: 10
seed: 42
metric_for_best_model: 'perplexity'
greater_is_better: false