# Model arguments
model_name_or_path: 'your_dir'
torch_dtype: bfloat16
trust_remote_code: True
attn_implementation: flash_attention_2  #sdpa

# Data training arguments
dataset_mixer:
  "Align_Cited_Text": 1.0
dataset_splits:
  - train
  - test
preprocessing_num_workers: 1
truncation_side: "left"

# DPOTrainer arguments
output_dir: 'your_dir'
num_train_epochs: 2
bf16: true
beta: 0.5
per_device_train_batch_size: 4  # 6 gpus: 4, 5 gpus: 4, 4 gpus: 2
per_device_eval_batch_size: 4
gradient_accumulation_steps: 8  # maintain bs*accu=32
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 5.0e-7
log_level: info
logging_steps: 2
logging_strategy: steps
optim: adamw_torch_fused  # paged_adamw_8bit  
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1600
overwrite_output_dir: true
remove_unused_columns: true
do_eval: true
# generate_during_eval: true
eval_strategy: steps
eval_steps: 10
run_name: ckpt-dpo-llama2
report_to:
  - wandb
save_strategy: "steps"
save_steps: 10
save_only_model: True
save_total_limit: 20
seed: 42
warmup_ratio: 0.1